/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserActivityService } from "../userActivity.service";
import { UserActivityCreateInput } from "./UserActivityCreateInput";
import { UserActivity } from "./UserActivity";
import { UserActivityFindManyArgs } from "./UserActivityFindManyArgs";
import { UserActivityWhereUniqueInput } from "./UserActivityWhereUniqueInput";
import { UserActivityUpdateInput } from "./UserActivityUpdateInput";

export class UserActivityControllerBase {
  constructor(protected readonly service: UserActivityService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserActivity })
  async createUserActivity(
    @common.Body() data: UserActivityCreateInput
  ): Promise<UserActivity> {
    return await this.service.createUserActivity({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [UserActivity] })
  @ApiNestedQuery(UserActivityFindManyArgs)
  async userActivities(
    @common.Req() request: Request
  ): Promise<UserActivity[]> {
    const args = plainToClass(UserActivityFindManyArgs, request.query);
    return this.service.userActivities({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserActivity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async userActivity(
    @common.Param() params: UserActivityWhereUniqueInput
  ): Promise<UserActivity | null> {
    const result = await this.service.userActivity({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserActivity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUserActivity(
    @common.Param() params: UserActivityWhereUniqueInput,
    @common.Body() data: UserActivityUpdateInput
  ): Promise<UserActivity | null> {
    try {
      return await this.service.updateUserActivity({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserActivity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUserActivity(
    @common.Param() params: UserActivityWhereUniqueInput
  ): Promise<UserActivity | null> {
    try {
      return await this.service.deleteUserActivity({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
