/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UserActivity } from "./UserActivity";
import { UserActivityCountArgs } from "./UserActivityCountArgs";
import { UserActivityFindManyArgs } from "./UserActivityFindManyArgs";
import { UserActivityFindUniqueArgs } from "./UserActivityFindUniqueArgs";
import { DeleteUserActivityArgs } from "./DeleteUserActivityArgs";
import { UserActivityService } from "../userActivity.service";
@graphql.Resolver(() => UserActivity)
export class UserActivityResolverBase {
  constructor(protected readonly service: UserActivityService) {}

  async _userActivitiesMeta(
    @graphql.Args() args: UserActivityCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UserActivity])
  async userActivities(
    @graphql.Args() args: UserActivityFindManyArgs
  ): Promise<UserActivity[]> {
    return this.service.userActivities(args);
  }

  @graphql.Query(() => UserActivity, { nullable: true })
  async userActivity(
    @graphql.Args() args: UserActivityFindUniqueArgs
  ): Promise<UserActivity | null> {
    const result = await this.service.userActivity(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserActivity)
  async deleteUserActivity(
    @graphql.Args() args: DeleteUserActivityArgs
  ): Promise<UserActivity | null> {
    try {
      return await this.service.deleteUserActivity(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
